ingress:
  hosts:
    - host: prime-text-staging.posmoni.com
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    - secretName: ai-staging.prime-tls
      hosts:
        - prime-text-staging.posmoni.com

components:
  api:
    resources:
      requests:
        cpu: 20m
        memory: 192Mi
      limits:
        cpu: 1100m
        memory: 512Mi
    hpa:
      minReplicas: 1
      maxReplicas: 1
    tolerations:
      - key: "enabled-to-run/in-karpenter"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      datawow.io/group: general
      datawow.io/architecture: x86
      intent: compute-optimized

  predictor:
    resources:
      requests:
        cpu: 15m
        memory: 1Gi
      limits:
        cpu: 1100m
        memory: 2Gi
    hpa:
      minReplicas: 1
      maxReplicas: 1
    tolerations:
      - key: "enabled-to-run/in-karpenter"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      datawow.io/group: general
      datawow.io/architecture: x86
      intent: compute-optimized

  worker:
    resources:
      requests:
        cpu: 10m
        memory: 64Mi
      limits:
        cpu: 1100m
        memory: 192Mi
    hpa:
      minReplicas: 1
      maxReplicas: 1
    tolerations:
      - key: "enabled-to-run/in-karpenter"
        operator: "Exists"
        effect: "NoSchedule"
    nodeSelector:
      datawow.io/group: general
      datawow.io/architecture: x86
      intent: compute-optimized
