apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: develop
bases:
- ../../../base/client-sample-app
patchesStrategicMerge:
- deployment.yaml
- ingress.yaml
- sa.yaml
resources:
- secret.yaml
# configurations:
#   - configuration/sealed-secret-config.yaml

images:
- name: 658721656416.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs-tutorialspoint-peerasilp
  newTag: latest
