apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: develop
bases:
- ../../../base/client-sample-app
patchesStrategicMerge:
- deployment.yaml
- sa.yaml
resources:
- secret.yaml
# configurations:
#   - configuration/sealed-secret-config.yaml

images:
- name: 123456789385.dkr.ecr.ap-southeast-1.amazonaws.com/client-staging-sample-app
  newTag: v1.0.11
