---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-sample-app
  name: client-sample
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # how many pods we can add at a time
      maxUnavailable: 0
      containers:
        - name: client-sample
          image: 658721656416.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs-tutorialspoint-peerasilp:latest

