apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: production
resources:
# - secret.yaml
- cronjob.yaml
- ../../../base/client-sample-app
# configurations:
#   - configuration/sealed-secret-config.yaml

images:
- name: 658721656416.dkr.ecr.ap-southeast-1.amazonaws.com/nodejs-tutorialspoint-peerasilp
  newTag: latest
patches:
- path: deployment.yaml
# - path: sa.yaml
- path: ingress.yaml
