apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: client-sample-app-secret
spec:
  provider: aws
  parameters:
    region: ap-southeast-1
    objects: |
      - objectName: "arn:aws:secretsmanager:ap-southeast-1:123456789385:secret:client-staging-eks-web/juhah-Nfm2P8"
        objectType: "secretsmanager"
